---
apiVersion: v1
kind: Namespace
metadata:
    name: cloudnative-webapp-adb
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: cloudnative-webapp-adb
  labels:
    tier: app
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: php
    tier: app
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cloudnative-webapp-adb
  labels:
    tier: web
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: nginx
    tier: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: cloudnative-webapp-adb
  labels:
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
      tier: app
  template:
    metadata:
      labels:
        app: php
        tier: app
    spec:
      containers:
      - name: php
        image: lhr.ocir.io/apaccpt01/php-adb:${BUILDRUN_HASH}
        env:
        - name: ADB_TNSNAME
          valueFrom:
            secretKeyRef:
              name: adb-secret
              key: ADB_TNSNAME
        - name: ADB_USER
          valueFrom:
            secretKeyRef:
              name: adb-secret
              key: ADB_USER
        - name: ADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adb-secret
              key: ADB_PASSWORD
        - name: TNS_ADMIN
          valueFrom:
            secretKeyRef:
              name: adb-secret
              key: TNS_ADMIN
        ports:
        - containerPort: 9000
      imagePullSecrets:
      - name: ocir-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: cloudnative-webapp-adb
  labels:
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
  template:
    metadata:
      labels:
        app: nginx
        tier: web
    spec:
      containers:
      - name: nginx
        image: lhr.ocir.io/apaccpt01/nginx-php:${BUILDRUN_HASH}
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ocir-secret
---