---
apiVersion: v1
kind: Namespace
metadata:
    name: cloudnative-webapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: cloudnative-webapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: cloudnative-webapp
  labels:
    tier: app
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: php
    tier: app
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cloudnative-webapp
  labels:
    tier: web
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: nginx
    tier: web
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cloudnative-webapp
  labels:
    tier: database
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
    tier: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: cloudnative-webapp
  labels:
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
      tier: app
  template:
    metadata:
      labels:
        app: php
        tier: app
    spec:
      containers:
      - name: php
        image: lhr.ocir.io/apaccpt01/php-webapp:0.10
        ports:
        - containerPort: 9000
      imagePullSecrets:
      - name: ocir-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: cloudnative-webapp
  labels:
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
  template:
    metadata:
      labels:
        app: nginx
        tier: web
    spec:
      containers:
      - name: nginx
        image: lhr.ocir.io/apaccpt01/nginx-php:0.2
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ocir-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cloudnative-webapp
  labels:
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysqlrootpassword
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysqldatabase
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysqluser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysqlpassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim